name: Super-Linter

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Also trigger on page_build, as well as release created events
  page_build:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  install-and-test:
    # Name the Job
    name: Install and run tests
    # Set the type of machine to run on
    runs-on: linux-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Run Install
#        run: |
#
#          composer install
#
#      - name: Run Static code Analysis
#        run: vendor/bin/phpstan analyse --error-format=github
#
#      - name: Run Unit Tests
#        run: vendor/phpunit/phpunit/phpunit

      # Runs the Super-Linter action
      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
